name: Build and deploy Node.js app to Azure Web App - winkmonaco

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: npm install, build, and test
        run: |
          npm install --legacy-peer-deps
          npm run build --if-present
          npm run test --if-present

      - name: Create a temporary directory
        run: |
          mkdir temp
        working-directory: ${{ github.workspace }}

      - name: Copy build artifacts to the temporary directory
        run: |
          cp -r * temp/
        working-directory: ${{ github.workspace }}

      - name: Create an archive in a temporary directory
        run: |
          # Sleep for 10 seconds to allow ongoing changes to finish
          sleep 10
          tar -czf node-app.tar.gz -C temp .
        working-directory: ${{ github.workspace }}

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: node-app.tar.gz

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'winkmonaco'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_624D119DA05847F5A7773751C75BBA25 }}
          package: node-app/node-app.tar.gz
