name: Build and deploy Node.js app to Azure Web App - winkmonaco

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: '18.x' # Use a compatible Node.js version

      - name: npm install, build, and test
        run: |
          npm install --legacy-peer-deps
          npm run build --if-present
          npm run test --if-present

      - name: Archive using zip
        run: |
          # Install 7-Zip
          choco install 7zip.portable -y
          
          # Create a zip archive of your build artifacts
          7z a -r -tzip node-app.zip .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: node-app.zip

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'winkmonaco'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_BE4DA4A540D443F79033824D1101420E }}
          package: node-app.zip
